default["rwci"]["user"]             = "rwci"
default["rwci"]["group"]            = "rwci"
default["rwci"]["rvm_ruby"]         = "ruby-1.9.3-p194"
default["rwci"]["rvm_gemset"]       = "rwci"
default["rwci"]["git"]["url"]       = "git://github.com/rashidkpc/Kibana.git"
default["rwci"]["git"]["reference"] = "v0.1.0"
